name: 'build'
on:
  workflow_dispatch:
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-20.04, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
          rustup target add aarch64-unknown-linux-gnu
              - name: install dependencies (ubuntu only)
      - name: install dependencies (macos only)
        if: matrix.platform == 'macos-latest'
        run: |
          rustup target add aarch64-apple-darwin
      - name: install dependencies (windows only)
        if: matrix.platform == 'macos-latest'
        run: |
          rustup target add i686-pc-windows-msvc
      - name: install app dependencies and build it
        run: yarn
        # windows 64
      - name: x64 build(windows only)
        if: matrix.platform == 'windows-latest'
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: dW50cnVzdGVkIGNvbW1lbnQ6IHJzaWduIGVuY3J5cHRlZCBzZWNyZXQga2V5ClJXUlRZMEl5LzczLzZwV2hOVlhsQVB1VDlJdTZMUnFmZUF3bnlGQjk1L00yZmRFMk4wSUFBQkFBQUFBQUFBQUFBQUlBQUFBQXBEak9kd0pMMEdEazdxVVVyVmV1SkZpakEyYVVubjB1ekpHV1VETkZsWXBOblVvY25zMEZOREgwT3JqRzM0bFErWEVDSHN0ZFZ0bmtrSk9qbXNxVFZ5ZE9jYU5Wd1VDNnhDdXhMQjRHWWJhZitsYjUwUk54a1Q5anRQemlyVlF5WjZITWtxcWw4SkU9Cg==
        with:
          tagName: app-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: 'App v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: true
          includeDebug: true
        # windows 32
      - name: x32 build (windows only)
        if: matrix.platform == 'windows-latest'
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: dW50cnVzdGVkIGNvbW1lbnQ6IHJzaWduIGVuY3J5cHRlZCBzZWNyZXQga2V5ClJXUlRZMEl5LzczLzZwV2hOVlhsQVB1VDlJdTZMUnFmZUF3bnlGQjk1L00yZmRFMk4wSUFBQkFBQUFBQUFBQUFBQUlBQUFBQXBEak9kd0pMMEdEazdxVVVyVmV1SkZpakEyYVVubjB1ekpHV1VETkZsWXBOblVvY25zMEZOREgwT3JqRzM0bFErWEVDSHN0ZFZ0bmtrSk9qbXNxVFZ5ZE9jYU5Wd1VDNnhDdXhMQjRHWWJhZitsYjUwUk54a1Q5anRQemlyVlF5WjZITWtxcWw4SkU9Cg==
        with:
          args: --target i686-pc-windows-msvc
          tagName: app-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: 'App v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: true
          includeDebug: true
        # linux 64
      - name: build (linux only)
        if: matrix.platform == 'ubuntu-20.04'
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: dW50cnVzdGVkIGNvbW1lbnQ6IHJzaWduIGVuY3J5cHRlZCBzZWNyZXQga2V5ClJXUlRZMEl5LzczLzZwV2hOVlhsQVB1VDlJdTZMUnFmZUF3bnlGQjk1L00yZmRFMk4wSUFBQkFBQUFBQUFBQUFBQUlBQUFBQXBEak9kd0pMMEdEazdxVVVyVmV1SkZpakEyYVVubjB1ekpHV1VETkZsWXBOblVvY25zMEZOREgwT3JqRzM0bFErWEVDSHN0ZFZ0bmtrSk9qbXNxVFZ5ZE9jYU5Wd1VDNnhDdXhMQjRHWWJhZitsYjUwUk54a1Q5anRQemlyVlF5WjZITWtxcWw4SkU9Cg==
        with:
          tagName: app-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: 'App v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: true
          includeDebug: true
        # linux arm64
      - name: arm64 build (linux only)
        if: matrix.platform == 'ubuntu-20.04'
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: dW50cnVzdGVkIGNvbW1lbnQ6IHJzaWduIGVuY3J5cHRlZCBzZWNyZXQga2V5ClJXUlRZMEl5LzczLzZwV2hOVlhsQVB1VDlJdTZMUnFmZUF3bnlGQjk1L00yZmRFMk4wSUFBQkFBQUFBQUFBQUFBQUlBQUFBQXBEak9kd0pMMEdEazdxVVVyVmV1SkZpakEyYVVubjB1ekpHV1VETkZsWXBOblVvY25zMEZOREgwT3JqRzM0bFErWEVDSHN0ZFZ0bmtrSk9qbXNxVFZ5ZE9jYU5Wd1VDNnhDdXhMQjRHWWJhZitsYjUwUk54a1Q5anRQemlyVlF5WjZITWtxcWw4SkU9Cg==
        with:
          args: --target aarch64-unknown-linux-gnu
          tagName: app-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: 'App v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: true
          includeDebug: true
        # macos silicon 
      - name: silicon build (macos only arm64)
        if: matrix.platform == 'macos-latest'
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: dW50cnVzdGVkIGNvbW1lbnQ6IHJzaWduIGVuY3J5cHRlZCBzZWNyZXQga2V5ClJXUlRZMEl5LzczLzZwV2hOVlhsQVB1VDlJdTZMUnFmZUF3bnlGQjk1L00yZmRFMk4wSUFBQkFBQUFBQUFBQUFBQUlBQUFBQXBEak9kd0pMMEdEazdxVVVyVmV1SkZpakEyYVVubjB1ekpHV1VETkZsWXBOblVvY25zMEZOREgwT3JqRzM0bFErWEVDSHN0ZFZ0bmtrSk9qbXNxVFZ5ZE9jYU5Wd1VDNnhDdXhMQjRHWWJhZitsYjUwUk54a1Q5anRQemlyVlF5WjZITWtxcWw4SkU9Cg==
        with:
          args: --target aarch64-apple-darwin
          tagName: app-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: 'App v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: true
          includeDebug: true
        # macos Intel
      - name: build (macos only x64)
        if: matrix.platform == 'macos-latest'
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: dW50cnVzdGVkIGNvbW1lbnQ6IHJzaWduIGVuY3J5cHRlZCBzZWNyZXQga2V5ClJXUlRZMEl5LzczLzZwV2hOVlhsQVB1VDlJdTZMUnFmZUF3bnlGQjk1L00yZmRFMk4wSUFBQkFBQUFBQUFBQUFBQUlBQUFBQXBEak9kd0pMMEdEazdxVVVyVmV1SkZpakEyYVVubjB1ekpHV1VETkZsWXBOblVvY25zMEZOREgwT3JqRzM0bFErWEVDSHN0ZFZ0bmtrSk9qbXNxVFZ5ZE9jYU5Wd1VDNnhDdXhMQjRHWWJhZitsYjUwUk54a1Q5anRQemlyVlF5WjZITWtxcWw4SkU9Cg==
        with:
          args: --target x86_64-apple-darwin
          tagName: app-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: 'App v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: true
          includeDebug: true